### ISSUE TITLE
ImportError: cannot import name 'datasets'

### ISSUE THREAD

**Issue by wanghao411** [Jarr0d/ViTAA#1]
when I run 'python tools/train_net.py --config-file configs/cuhkpedes/bilstm_r50_seg.yaml', The following errors occurred:
Traceback (most recent call last):
  File "tools/train_net.py", line 23, in <module>
    from vitaa.data import make_data_loader
  File "./vitaa/data/__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "./vitaa/data/build.py", line 7, in <module>
    from . import datasets as D
ImportError: cannot import name 'datasets'
According to these problems, I can't find datasets in "./vitaa/data"
How to solve this problem?

**Comment by Jarr0d** [comment]
We want to ignore the ./dataset file, but the command in .gitignore accidentally ignore the ./vitaa/data/dataset.
The bug has been fixed. Thanks for your patience.
