### ISSUE TITLE
How does HRNet implement ot generate attributes?

### ISSUE THREAD

**Issue by 0shelter0** [Jarr0d/ViTAA#7]
Hello, thanks for your great work! I just want to know the details about HRNet implementation, beacause I can't find anything to do with HRNet in your codebase. 

Looking forward your reply, thank your very lot.

**Comment by Jarr0d** [comment]
Check this repo https://github.com/Jarr0d/Human-Parsing-Network

**Comment by 0shelter0** [comment]
Thank you very much!
